
package soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IProducts", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IProducts {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://soap/", className = "soap.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://soap/", className = "soap.GetProductResponse")
    @Action(input = "http://soap/IProducts/getProductRequest", output = "http://soap/IProducts/getProductResponse")
    public String getProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
